name: "Set Branch Protection Rules"

on:
  push:
    branches: [ main ]

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Branch Protection Rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const branches = ['main', 'develop'];
            
            for (const branch of branches) {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.name,
                branch: branch,
                required_status_checks: {
                  strict: true,
                  contexts: ['Validate Code', 'Code Quality', 'Security Scan']
                },
                enforce_admins: true,
                required_pull_request_reviews: null,
                restrictions: {
                  users: [],
                  teams: [],
                  apps: []
                },
                required_linear_history: true,
                allow_force_pushes: false,
                allow_deletions: false,
                required_conversation_resolution: true,
                required_signatures: true
              });
              
              console.log(`Branch protection rules set for ${branch}`);
            } 