name: "Branch Protection"
on:
  push:
    branches:
      - main
jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Branch Protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const branches = ['main', 'develop'];
            for (const branch of branches) {
              try {
                console.log(`Setting up protection rules for ${branch} branch...`);
                await github.rest.repos.updateBranchProtection({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  branch: branch,
                  required_status_checks: null,
                  enforce_admins: true,
                  required_pull_request_reviews: {
                    dismiss_stale_reviews: true,
                    require_code_owner_reviews: false,
                    required_approving_review_count: 1
                  },
                  restrictions: {
                    users: [],
                    teams: [],
                    apps: []
                  },
                  allow_force_pushes: false,
                  allow_deletions: false
                });
                console.log(`Successfully protected ${branch} branch`);
              } catch (error) {
                console.log(`Error protecting ${branch} branch:`, error.message);
                core.setFailed(error.message);
              }
            } 