name: "Branch Protection"
on:
  push:
    branches:
      - main
jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Branch Protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branches = ['main', 'develop'];
            
            for (const branch of branches) {
              try {
                console.log(`Setting up protection rules for ${branch} branch...`);
                
                // Update branch protection
                await github.rest.repos.updateBranchProtection({
                  owner,
                  repo,
                  branch,
                  required_status_checks: {
                    strict: true,
                    contexts: ['validate']
                  },
                  enforce_admins: false,
                  required_pull_request_reviews: null,
                  restrictions: null,
                  allow_force_pushes: false,
                  allow_deletions: false,
                  required_linear_history: true
                });
                
                console.log(`Successfully protected ${branch} branch`);
              } catch (error) {
                console.error(`Error protecting ${branch} branch:`, error);
                core.setFailed(`Failed to protect ${branch} branch: ${error.message}`);
              }
            } 