name: Verify Commits

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  verify-commits:
    name: Verify Commit Signatures
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Verify commit signatures
        run: |
          git verify-commit HEAD^{commit} 2>&1 | grep -q "Good signature"
          if [ $? -eq 0 ]; then
            echo "✅ Commit is signed"
            exit 0
          else
            echo "❌ Commit is not signed"
            echo "Please sign your commits using GPG key"
            echo "Follow the guide: https://docs.github.com/en/authentication/managing-commit-signature-verification"
            exit 1
          fi 